version: "3"

services:
  # ultrahook service uses config file
    ultrahook:
      image: usgsastro/ultrahook:latest
      env_file: /var/lib/dockervols/ultrahook/config.yml
      restart: unless-stopped
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role == worker]
